# Generated by Django 3.2.16 on 2024-05-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['author__username']},
        ),
    ]
