# Generated by Django 3.2.16 on 2024-05-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20240528_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['author__username']},
        ),
    ]
